chat-language: english
voice-language: english

dark-mode: true
code-theme: monokai
attribute-author: false
attribute-committer: false

architect: true

check-update: true

alias:
  - "fast:openrouter/google/gemini-2.5-flash-preview"
  - "smart:openrouter/google/gemini-2.5-pro-preview"

# default models if not chosen via CLI
model: smart
