- name: openrouter/google/gemini-2.5-pro-preview-03-25
  edit_format: diff-fenced
  overeager: true
  use_repo_map: true
  weak_model_name: openrouter/google/gemini-2.5-flash-preview

- name: openrouter/google/gemini-2.5-flash-preview
  edit_format: diff
  use_repo_map: true
  accepts_settings: ["thinking_tokens"]
