#! /bin/sh

# Config 
bspc config border_width                2
bspc config window_gap                  12
bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config initial_polarity            'second_child'
bspc config normal_border_color         '#ffffff'
bspc config focused_border_color        '#55aaff'

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Peek state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Setup
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
polybar main &
bash ~/.config/bspwm/monitors.sh
