#! /bin/sh

# Config 
bspc config border_width                2
bspc config window_gap                  12
bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config initial_polarity            'second_child'
bspc config normal_border_color         '#ffffff'
bspc config focused_border_color        '#55aaff'
bspc config active_border_color         '#aaddff'

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Peek state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Setup Monitors
bash ~/.config/bspwm/monitors.sh
