min = 1
max = 10
remove-empty = true
append-when-occupied = true
watch-config = true
renamers = ["classified", "constant"]

[names]
constant = "new"

[[names.classified]]
"code" = ["Emacs"]

[[names.classified]]
"android" = ["Emulator", "qemu", "jetbrains-studio", "React Native Debugger"]

[[names.classified]]
"games" = ["Steam"]

[[names.classified]]
"chat-work" = ["Slack", "hiri"]

[[names.classified]]
"chat" = ["discord", "WhatsApp", "Caprine"]

[[names.classified]]
"meeting" = ["zoom"]

[[names.classified]]
"todo" = ["Todoist"]

[[names.classified]]
"files" = ["Pcmanfm"]

[[names.classified]]
"video" = ["YouTube", "mpv", "qutebrowser"]

[[names.classified]]
"firefox" = ["Firefox", "Firefox Developer Edition", "Navigator"]

[[names.classified]]
"chrome" = ["Chromium", "Chrome", "Google"]

[[names.classified]]
"music" = ["Spotify", ""] # well done spotify *facepalm*

[[names.classified]]
"term" = ["xterm", "st", "Alacritty", "URxvt"]
