# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json

os:
  editPreset: "nvim"
  # editPreset: "nvim-remote" # better for me, but not released yet
update:
  method: "background"
  days: 7

gui:
  nerdFontsVersion: "3"
  # Use the mocha catppuccin theme
  theme:
    activeBorderColor:
      - "#89dceb"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89dceb"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#b4befe"
