#! /bin/sh

# Config
bspc config border_width                2
bspc config window_gap                  16
bspc config split_ratio                 0.5
bspc config borderless_monocle          false
bspc config gapless_monocle             false
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config initial_polarity            'second_child'
bspc config normal_border_color         '#ffffff'
bspc config focused_border_color        '#55aaff'
bspc config active_border_color         '#aaddff'

# Rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a Peek state=floating
bspc rule -a Emacs state=tiled

# Setup Monitors
#autorandr -c
bash ~/.config/bspwm/monitors.sh
btops &

# fix espanso bug
systemctl --user restart espanso.service
