# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 1000 # 1 second for command timeout

# Old custom format
format = """
[█](black)$character$status$cmd_duration[](black)\
$jobs\
$kubernetes\
$aws\
$directory\
([](bright-yellow)$git_branch$git_metrics$git_status[](bright-yellow))\
$line_break\
[█](black)\
$nix_shell\
$nodejs\
$terraform\
$rust\
$python\
$ruby\
[](bright-black)[](bright-red)[](bright-green)[](bright-yellow)[](bright-cyan) """

[character]
success_symbol = "[✓](bold green)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[](bright-white)"
format = " $symbol "

[cmd_duration]
min_time = 0
format = "([$duration]($style))"
style = "bold yellow"

[status]
disabled = false
format = "([$status ]($style))"
style = "bold red"

[jobs]
symbol = "省"
format = "([](purple)[$symbol$number]($style)[](purple))"
style = "white bg:purple"

[directory]
truncate_to_repo = true
truncation_length = 2
fish_style_pwd_dir_length = 1
format = "([  $path ]($style))"
style = "bright-cyan"

[nix_shell]
disabled = true
symbol = ""
format = "[](cyan)[$symbol $state]($style)[](cyan)"
style = "black bg:cyan"

[nodejs]
format = "([](green)[$symbol$version]($style)[](green))"
version_format = "$raw"
style = "black bg:green"
not_capable_style = "#cc0033 bg:green"

[terraform]
symbol = "[TF](bold $style)"
format = "([](blue)[$symbol $workspace]($style)[](blue))"
style = "white bg:blue"

[kubernetes]
disabled = true
symbol = "ﴱ"
format = '([](bright-red)[$symbol $context( \[$namespace\])]($style)[](bright-red))'
style = "black bg:bright-red"
context_aliases = { kind-kind = "kind" }

[aws]
disabled = false
symbol = ""
format = '([](bright-red)[$symbol $profile( \[$duration\])]($style)[](bright-red))'
style = "black bg:bright-red"

[golang]
symbol = ""
version_format = "$raw"
format = "([](cyan)[$symbol $version]($style)[](cyan))"
style = "black bg:cyan"

[rust]
version_format = "$raw"
format = "([](bright-black)[$symbol$version]($style)[](bright-black))"
style = "red bg:bright-black"

[python]
version_format = "$raw"
format = "([](yellow)[$symbol$version]($style)[](yellow))"
style = "black bg:yellow"

[ruby]
version_format = "$raw"
symbol = " "
format = "([](red)[$symbol$version]($style)[](red))"
style = "black bg:red"

[git_branch]
symbol = ""
truncation_length = 32
format = "([$symbol $branch]($style))"
style = "black bg:bright-yellow"

[git_metrics]
disabled = false
format = "([ ](bg:bright-yellow)[+$added]($added_style)[-$deleted]($deleted_style))"
added_style = "bright-black bg:bright-yellow"
deleted_style = "red bg:bright-yellow"

[git_status]
deleted = "x"
format = "([ $all_status$ahead_behind ]($style))"
style = "bold red bg:bright-yellow"
ignore_submodules = true
