# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_mocha"

# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 2000 # 1 second for command timeout

# Old custom format
format = """
$character$status$cmd_duration\
$jobs\
$kubernetes\
$aws\
$directory\
([](yellow)$git_branch$git_metrics$git_status[](yellow))\
$line_break\
$nix_shell\
$nodejs\
$terraform\
$rust\
$golang\
$python\
$ruby\
[](rosewater) """

[character]
success_symbol = "[✓](bold green)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[](text)"
format = "$symbol "

[cmd_duration]
min_time = 0
format = "([$duration]($style)) "
style = "bold yellow"

[status]
disabled = false
format = "([$status ]($style)) "
style = "bold red"

[jobs]
symbol = "省"
format = "([](mauve)[$symbol$number]($style)[](mauve)) "
style = "text bg:mauve"

[directory]
truncate_to_repo = true
truncation_length = 2
fish_style_pwd_dir_length = 1
format = "([  $path]($style)) "
style = "sky"

[nix_shell]
disabled = true
symbol = ""
format = "[](sapphire)[$symbol $state]($style)[](sapphire) "
style = "crust bg:sapphire"

[nodejs]
format = "([](green)[$symbol$version]($style)[](green)) "
symbol = " "
version_format = "$raw"
style = "crust bg:green"
not_capable_style = "#cc0033 bg:green"

[terraform]
symbol = "[TF](bold $style)"
format = "([](blue)[$symbol $workspace]($style)[](blue)) "
style = "text bg:blue"

[kubernetes]
disabled = false
symbol = ""
format = '([](maroon)[$symbol $context( \[$namespace\])]($style)[](maroon)) '
style = "crust bg:maroon"

[aws]
disabled = true
symbol = ""
format = '([](maroon)[$symbol $profile( \[$duration\])]($style)[](maroon)) '
style = "crust bg:maroon"

[golang]
symbol = "󰟓"
version_format = "$raw"
format = "([](sapphire)[$symbol $version]($style)[](sapphire)) "
style = "crust bg:sapphire"

[rust]
version_format = "$raw"
format = "([](mantle)[$symbol$version]($style)[](mantle)) "
style = "red bg:mantle"

[python]
version_format = "$raw"
format = "([](yellow)[$symbol$version]($style)[](yellow)) "
style = "crust bg:yellow"

[ruby]
version_format = "$raw"
symbol = " "
format = "([](red)[$symbol$version]($style)[](red)) "
style = "crust bg:red"

[git_branch]
symbol = ""
truncation_length = 32
format = "([$symbol $branch]($style))"
style = "crust bg:yellow"

[git_metrics]
disabled = false
format = "([ ](bg:yellow)[+$added]($added_style)[-$deleted]($deleted_style))"
added_style = "mantle bg:yellow"
deleted_style = "red bg:yellow"

[git_status]
deleted = "x"
format = "([ $all_status$ahead_behind ]($style))"
style = "bold red bg:yellow"
ignore_submodules = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
