#!/usr/bin/env lua

-- This is only needed once to install the sketchybar module
-- (or for an update of the module)
-- os.execute(
-- 	"[ ! -d $HOME/.local/share/sketchybar_lua/ ] && (git clone https://github.com/FelixKratz/SbarLua.git /tmp/SbarLua && cd /tmp/SbarLua/ && make install && rm -rf /tmp/SbarLua/)"
-- )

-- Add the sketchybar module to the package cpath (the module could be
-- installed into the default search path then this would not be needed)
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

require("init")

-- # ##### Adding Left Items #####
-- # # We add some regular items to the left side of the bar, where
-- # # only the properties deviating from the current defaults need to be set
-- #
-- # sketchybar --add item chevron left \
-- #            --set chevron icon= label.drawing=off \
-- #            --add item front_app left \
-- #            --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
-- #            --subscribe front_app front_app_switched
-- #
-- # ##### Adding Items next to the notch #####
-- # # This is mostly going to be aliases to the native MacOS menu bar items
-- #
-- # sketchybar --add alias Tunnelblick q \
-- #            --set Tunnelblick label.drawing=off icon.drawing=off \
-- #            --add alias AeroSpace e \
-- #            --set AeroSpace label.drawing=off icon.drawing=off
-- #
-- # ##### Adding Right Items #####
-- # # In the same way as the left items we can add items to the right side.
-- # # Additional position (e.g. center) are available, see:
-- # # https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar
-- #
-- # # Some items refresh on a fixed cycle, e.g. the clock runs its script once
-- # # every 10s. Other items respond to events they subscribe to, e.g. the
-- # # volume.sh script is only executed once an actual change in system audio
-- # # volume is registered. More info about the event system can be found here:
-- # # https://felixkratz.github.io/SketchyBar/config/events
-- #
-- # # TODO: add some CPU, mem, etc monitors, perhaps with a graph over time
-- # # TODO: add some more icons for status of Bluetooth, VPN, WiFi, etc
-- # # TODO: add some indicators for number of Slack messages, emails, PRs to review, etc
-- # sketchybar --add item clock right \
-- #            --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
-- #            --add item volume right \
-- #            --set volume script="$PLUGIN_DIR/volume.sh" \
-- #            --subscribe volume volume_change \
-- #            --add item battery right \
-- #            --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
-- #            --subscribe battery system_woke power_source_change
-- #
-- # ##### Force all scripts to run the first time (never do this in a script) #####
-- # sketchybar --update
